import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/material-tailwind-theme-provider';
import ReactQueryClientProviders from '@/config/ReactQueryClientProvider';
import RecoilProvider from '@/config/RecoilProvider';
import MainLayout from '@/components/layouts/main-layout';
import Auth from '@/components/auth';
import { createServerSupabaseClient } from '@/utils/supabase/server';
import AuthProvider from '@/config/auth-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const supabase = await createServerSupabaseClient();

  const {
    data: { session },
  } = await supabase.auth.getSession();
  console.log('session : ', session);

  return (
    <RecoilProvider>
      <ReactQueryClientProviders>
        <ThemeProvider>
          {/* @ts-ignore */}
          <html lang="en">
            <head>
              <link
                rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
                integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
                crossOrigin="anonymous"
                referrerPolicy="no-referrer"
              />
            </head>
            <AuthProvider accessToken={session?.access_token}>
              <body className={inter.className}>
                {session?.user ? <MainLayout>{children}</MainLayout> : <Auth />}
              </body>
            </AuthProvider>
          </html>
        </ThemeProvider>
      </ReactQueryClientProviders>
    </RecoilProvider>
  );
}

// session :  {
//   access_token: 'eyJhbGciOiJIUzI1NiIsImtpZCI6IitIdWhpWVlYSXFqcVVvdWUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NrbXlmd21ycHZwa3VzaHBlbGRhLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlNjRjZWYxNi00YmRlLTQzZDUtODJmNy0zYWI5MmFkNGM1NzgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU0MjY1NzM3LCJpYXQiOjE3NTQyNjIxMzcsImVtYWlsIjoiY29wcGVyNUBkYXVtLm5ldCIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJjb3BwZXI1QGRhdW0ubmV0IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiZTY0Y2VmMTYtNGJkZS00M2Q1LTgyZjctM2FiOTJhZDRjNTc4In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoiZW1haWwvc2lnbnVwIiwidGltZXN0YW1wIjoxNzU0MjYyMTM3fV0sInNlc3Npb25faWQiOiIyMDRhNGMyZC00ZTM3LTQ5OWYtODk4Yi1lNzA1ZGY4ZDdlYmUiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.ZQzPxVH5tkPX7DG5MZhkNxra7Jq-rIQbtK5bYxPJY_Y',
//   token_type: 'bearer',
//   expires_in: 3600,
//   expires_at: 1754265737,
//   refresh_token: '7s4qosqxa4gi',
//   user: {
//     id: 'e64cef16-4bde-43d5-82f7-3ab92ad4c578',
//     aud: 'authenticated',
//     role: 'authenticated',
//     email: 'copper5@daum.net',
//     email_confirmed_at: '2025-08-03T23:02:16.390147Z',
//     phone: '',
//     confirmation_sent_at: '2025-08-03T23:01:49.001428Z',
//     confirmed_at: '2025-08-03T23:02:16.390147Z',
//     last_sign_in_at: '2025-08-03T23:02:17.445508903Z',
//     app_metadata: { provider: 'email', providers: [Array] },
//     user_metadata: {
//       email: 'copper5@daum.net',
//       email_verified: true,
//       phone_verified: false,
//       sub: 'e64cef16-4bde-43d5-82f7-3ab92ad4c578'
//     },
//     identities: [ [Object] ],
//     created_at: '2025-08-03T23:01:48.922872Z',
//     updated_at: '2025-08-03T23:02:17.482988Z',
//     is_anonymous: false
//   }
// }
